#!/usr/bin/env python3
"""
Generate the Granger-causality LaTeX table from saved artifacts.

The script reads saved research outputs only. It first tries the plain-text
output produced by machine_learning_for_crypto_v6/granger_trump.py. If that is
not available, it falls back to the saved CSV table in R12723071/Output.
"""

import csv
import os
import re

PAPER_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
REPO_DIR = os.path.abspath(os.path.join(PAPER_DIR, '..'))
V6_DIR = os.path.join(REPO_DIR, 'machine_learning_for_crypto_v6')
SUBMISSION_DIR = os.path.join(REPO_DIR, 'R12723071')
TABLE_DIR = os.path.join(PAPER_DIR, 'tables')
os.makedirs(TABLE_DIR, exist_ok=True)

GRANGER_FILE = os.path.join(V6_DIR, 'outputs', 'granger_output.txt')
CSV_FALLBACK = os.path.join(SUBMISSION_DIR, 'Output', 'Table_7_2_granger.csv')

FEATURE_LABELS = {
    'trump_post_count': 'Post count',
    'trump_caps_ratio': 'Caps ratio',
    'trump_tariff_score': 'Tariff score',
    'trump_crypto_score': 'Crypto score',
    'trump_sentiment': 'Sentiment',
}


def parse_granger_output(filepath):
    """Parse the text output produced by granger_trump.py."""
    if not os.path.exists(filepath):
        return None

    with open(filepath, encoding='utf-8') as f:
        text = f.read()

    blocks = re.split(r'Target:\s+', text)
    mean_block = None
    for block in blocks:
        if block.strip().startswith('Cross-sectional mean return'):
            mean_block = block
            break
    if mean_block is None:
        return None

    pattern = re.compile(
        r'^\s{4}(\w+)\s+'
        r'([\d.]+)\s+'
        r'([\d.]+)\s+'
        r'(\S*)\s*'
        r'\u2502\s+'
        r'([\d.]+)\s+'
        r'([\d.]+)\s+'
        r'lag=(\d+)',
        re.MULTILINE,
    )

    results = []
    for m in pattern.finditer(mean_block):
        results.append({
            'feature': m.group(1),
            'label': FEATURE_LABELS.get(m.group(1), m.group(1).replace('_', r'\_')),
            'f_lag1': float(m.group(2)),
            'p_lag1': float(m.group(3)),
            'sig_lag1': m.group(4).strip(),
            'f_best': float(m.group(5)),
            'p_best': float(m.group(6)),
            'best_lag': int(m.group(7)),
        })
    return results if results else None


def parse_saved_csv(filepath):
    """Read the saved Table 7.2 CSV artifact."""
    if not os.path.exists(filepath):
        return None

    results = []
    with open(filepath, encoding='utf-8') as f:
        for row in csv.DictReader(f):
            lag_text = row.get('Best_Lag_Sig', '')
            lag_match = re.search(r'lag=(\d+)', lag_text)
            results.append({
                'feature': row.get('Feature', ''),
                'label': row.get('Feature', ''),
                'f_lag1': float(row['Lag1_F']),
                'p_lag1': float(row['Lag1_p']),
                'sig_lag1': row.get('Lag1_Sig', '').strip(),
                'f_best': float(row['Best_F']),
                'p_best': float(row['Best_p']),
                'best_lag': int(lag_match.group(1)) if lag_match else None,
            })
    return results if results else None


def sig_stars(p):
    if p < 0.01:
        return r'$^{***}$'
    if p < 0.05:
        return r'$^{**}$'
    if p < 0.10:
        return r'$^{*}$'
    return ''


def gen_table(results):
    lines = []
    lines.append('% Auto-generated by gen_granger_table.py')
    lines.append(r'\begin{table}[t]')
    lines.append(r'\centering')
    lines.append(
        r'\caption{Granger causality tests: Trump social media features '
        r'$\to$ cross-sectional mean weekly return. '
        r'Columns report $F$-statistics and $p$-values at lag~1 and at '
        r'the best lag (minimising the $p$-value over $p \in \{1,2,4\}$). '
        r'VAR($p$) estimated on Trump-period weeks only ($T=112$).}'
    )
    lines.append(r'\label{tab:granger}')
    lines.append(r'\small')
    lines.append(r'\begin{tabular}{lrrlrrl}')
    lines.append(r'\toprule')
    lines.append(
        r'\multirow{2}{*}{\thead{Feature}} & '
        r'\multicolumn{3}{c}{\thead{Lag 1}} & '
        r'\multicolumn{3}{c}{\thead{Best lag}} \\'
    )
    lines.append(r'\cmidrule(lr){2-4}\cmidrule(lr){5-7}')
    lines.append(
        r' & \thead{$F$} & \thead{$p$} & \thead{Sig.} '
        r'& \thead{$F$} & \thead{$p$} & \thead{Lag/Sig.} \\'
    )
    lines.append(r'\midrule')

    for row in results:
        label = row.get('label') or FEATURE_LABELS.get(
            row['feature'], row['feature'].replace('_', r'\_'))
        lag_sig = (
            f"lag={row['best_lag']}{sig_stars(row['p_best'])}"
            if row.get('best_lag') is not None else sig_stars(row['p_best'])
        )
        lines.append(
            f"{label} & {row['f_lag1']:.3f} & {row['p_lag1']:.4f} & "
            f"{sig_stars(row['p_lag1'])} & {row['f_best']:.3f} & "
            f"{row['p_best']:.4f} & {lag_sig} \\\\"
        )

    lines.append(r'\bottomrule')
    lines.append(r'\end{tabular}')
    lines.append(r'\par\vspace{0.35em}')
    lines.append(r'\begin{minipage}{0.96\linewidth}')
    lines.append(r'\raggedright\footnotesize')
    lines.append(
        r'\textit{Note:} The null hypothesis is that the Trump feature does '
        r'not Granger-cause the cross-sectional mean weekly return. '
        r'$^{***}$/$^{**}$/$^{*}$ denote significance at 1\%/5\%/10\% '
        r'levels; an empty significance cell means $p \geq 0.10$. '
        r'The best-lag column searches over $\{1,2,4\}$ weekly lags. '
        r'No multiple-testing adjustment is applied.'
    )
    lines.append(r'\end{minipage}')
    lines.append(r'\end{table}')
    return '\n'.join(lines) + '\n'


def main():
    path = os.path.join(TABLE_DIR, 'table_granger.tex')

    results = parse_granger_output(GRANGER_FILE)
    source = GRANGER_FILE
    if results is None:
        results = parse_saved_csv(CSV_FALLBACK)
        source = CSV_FALLBACK
    if results is None:
        print(f"  [SKIP] Could not parse {GRANGER_FILE} or {CSV_FALLBACK}")
        with open(path, 'w', encoding='utf-8') as f:
            f.write('% Placeholder: saved Granger output was not available.\n')
        return

    with open(path, 'w', encoding='utf-8') as f:
        f.write(gen_table(results))
    print(f"  Saved: {path} (source: {source})")


if __name__ == '__main__':
    print("=== Generating Granger causality table ===")
    main()
    print("=== Done ===")
