#!/usr/bin/env python3
"""
gen_tables.py -- Generate LaTeX table fragments from saved paper results.

The script reads saved checkpoints only; it does not retrain models.
It resolves paths in this order:
  1. PAPER_CHECKPOINT_DIR / PAPER_OUTPUT_DIR environment variables
  2. machine_learning_for_crypto_v6 local outputs
  3. R12723071 submission outputs
"""

import csv
import json
import os
import sys

PAPER_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
REPO_DIR = os.path.abspath(os.path.join(PAPER_DIR, '..'))
V6_DIR = os.path.join(REPO_DIR, 'machine_learning_for_crypto_v6')
SUBMISSION_DIR = os.path.join(REPO_DIR, 'R12723071')
TABLE_DIR = os.path.join(PAPER_DIR, 'tables')
os.makedirs(TABLE_DIR, exist_ok=True)

sys.path.insert(0, V6_DIR)
from evaluate import (  # noqa: E402
    load_results,
    compute_portfolio_metrics,
    compute_sr_after_costs,
    find_breakeven_cost,
)


MODEL_FILES = {
    'cs_gated': 'cs_gated_results.npz',
    'lstm': 'lstm_results.npz',
    'tft': 'tft_results.npz',
    'ols': 'ols_results.npz',
    'elasticnet': 'elasticnet_results.npz',
    'pca_regression': 'pca_regression_results.npz',
    'pls': 'pls_results.npz',
    'random_forest': 'random_forest_results.npz',
    'gradient_boosting': 'gradient_boosting_results.npz',
}

DISPLAY = {
    'cs_gated': 'CS\\_Gated',
    'lstm': 'LSTM',
    'tft': 'TFT',
    'ols': 'OLS',
    'elasticnet': 'ElasticNet',
    'pca_regression': 'PCA',
    'pls': 'PLS',
    'random_forest': 'RF',
    'gradient_boosting': 'GBT',
}

MODEL_ORDER = [
    'cs_gated', 'lstm', 'tft', 'ols', 'elasticnet',
    'pca_regression', 'pls', 'random_forest', 'gradient_boosting',
]


def _load_config():
    candidates = [
        os.environ.get('PAPER_CONFIG'),
        os.path.join(V6_DIR, 'config.json'),
        os.path.join(SUBMISSION_DIR, 'Codes', 'config.json'),
    ]
    path = next((p for p in candidates if p and os.path.exists(p)), None)
    if path is None:
        raise FileNotFoundError('Could not find config.json.')
    with open(path, encoding='utf-8') as f:
        return json.load(f)


CFG = _load_config()
FEAT_CONFIGS = CFG['feature_configs']
FEAT_NAMES = list(FEAT_CONFIGS.keys())


def _resolve_checkpoint_dir():
    candidates = [
        os.environ.get('PAPER_CHECKPOINT_DIR'),
        os.path.join(V6_DIR, CFG.get('output_dir', 'checkpoints')),
        os.path.join(V6_DIR, 'checkpoints'),
        os.path.join(SUBMISSION_DIR, 'Codes', 'checkpoints'),
    ]
    required = [MODEL_FILES[m] for m in MODEL_ORDER]
    for candidate in candidates:
        if not candidate:
            continue
        candidate = os.path.abspath(candidate)
        if all(os.path.exists(os.path.join(candidate, name)) for name in required):
            return candidate
    raise FileNotFoundError('Could not find saved paper checkpoints.')


def _output_dirs():
    candidates = [
        os.environ.get('PAPER_OUTPUT_DIR'),
        os.path.join(V6_DIR, 'outputs'),
        os.path.join(SUBMISSION_DIR, 'Output'),
    ]
    return [os.path.abspath(p) for p in candidates if p and os.path.isdir(p)]


CKPT_DIR = _resolve_checkpoint_dir()
OUTPUT_DIRS = _output_dirs()


def _latex_info_set(name):
    return name.replace('+', r'{+}')


def _ci_excludes_zero(ci):
    lo, hi = ci
    return lo > 0 or hi < 0


def _fmt_sr(value, ci=None, bold=False):
    body = f'{value:.3f}'
    if ci is not None and _ci_excludes_zero(ci):
        body += r'$^\dagger$'
    return rf'\textbf{{{body}}}' if bold else body


def _load_all_metrics():
    metrics = {}
    for model in MODEL_ORDER:
        npz_path = os.path.join(CKPT_DIR, MODEL_FILES[model])
        results, _, _, _ = load_results(npz_path, FEAT_CONFIGS)
        model_metrics = {}
        for feat_name, res in results.items():
            model_metrics[feat_name] = compute_portfolio_metrics(
                res['ensemble_preds'],
                res['ensemble_tgts'],
                res['ensemble_msks'],
            )
        metrics[model] = model_metrics
    return metrics


def gen_cross_model():
    """Generate the main cross-model comparison table from checkpoints."""
    metrics = _load_all_metrics()
    n_models = len(MODEL_ORDER)
    col_spec = 'l' + 'r' * n_models

    lines = []
    lines.append('% Auto-generated by gen_tables.py -- do not edit manually')
    lines.append(r'\begin{table*}[t]')
    lines.append(r'\centering')
    lines.append(
        r'\caption{Cross-model comparison: annualised Sharpe ratios on the '
        r'test set. The held-out period contains 49 panel weeks; after '
        r'masking, portfolio metrics use 48 valid weekly long-short returns.}'
    )
    lines.append(r'\label{tab:cross_model}')
    lines.append(r'\begingroup')
    lines.append(r'\footnotesize')
    lines.append(r'\setlength{\tabcolsep}{3pt}')
    lines.append(r'\begin{tabular}{@{}' + col_spec + r'@{}}')
    lines.append(r'\toprule')

    header = r'\thead{Information Set}'
    for model in MODEL_ORDER:
        header += f' & \\thead{{{DISPLAY[model]}}}'
    header += r' \\'
    lines.append(header)

    for panel, key, label in [
        ('Panel A', 'ew', 'Equal-Weight (EW)'),
        ('Panel B', 'pw', 'Price-Weighted (PW)'),
    ]:
        lines.append(r'\midrule')
        lines.append(
            rf'\multicolumn{{{n_models + 1}}}{{l}}{{\textit{{{panel}: {label}}}}} \\'
        )
        lines.append(r'\midrule')
        sr_key = f'sr_{key}'
        ci_key = f'sr_ci_{key}'
        for feat_name in FEAT_NAMES:
            values = [metrics[m][feat_name][sr_key] for m in MODEL_ORDER]
            max_value = max(values)
            line = _latex_info_set(feat_name)
            for model, value in zip(MODEL_ORDER, values):
                ci = metrics[model][feat_name][ci_key]
                line += f' & {_fmt_sr(value, ci, bold=(value == max_value))}'
            line += r' \\'
            lines.append(line)

    lines.append(r'\bottomrule')
    lines.append(r'\end{tabular}')
    lines.append(r'\endgroup')
    lines.append(r'\par\vspace{0.35em}')
    lines.append(r'\begin{minipage}{0.96\linewidth}')
    lines.append(r'\raggedright\footnotesize')
    lines.append(
        r'\textit{Note:} $\dagger$ indicates that the 95\% circular '
        r'block-bootstrap confidence interval for the annualised Sharpe ratio '
        r'excludes zero. Bootstrap block length is '
        r'$b=\max(2,\lfloor T^{1/3}\rfloor)$. Bold entries mark the best '
        r'model within each information set and weighting scheme.'
    )
    lines.append(r'\end{minipage}')
    lines.append(r'\end{table*}')

    path = os.path.join(TABLE_DIR, 'table_cross_model.tex')
    with open(path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    print(f"  Saved: {path}")


def gen_ablation():
    """Generate ablation study table from the saved CSV when available."""
    csv_path = None
    for output_dir in OUTPUT_DIRS:
        for filename in ['Table_7_1_ablation.csv', 'ablation_study.csv']:
            candidate = os.path.join(output_dir, filename)
            if os.path.exists(candidate):
                csv_path = candidate
                break
        if csv_path is not None:
            break
    if csv_path is None:
        print(f"  [SKIP] ablation CSV not found in {OUTPUT_DIRS}")
        return

    with open(csv_path, encoding='utf-8') as f:
        rows = list(csv.DictReader(f))

    lines = []
    lines.append('% Auto-generated by gen_tables.py')
    lines.append(r'\begin{table}[t]')
    lines.append(r'\centering')
    lines.append(
        r'\caption{Ablation study of the LSTM pipeline on '
        r'\texttt{Price+Technical} (32 seeds per variant). Ensemble SR is '
        r'computed after averaging predictions across all seeds; Mean Seed SR '
        r'and Seed SD summarize single-seed performance. $\Delta$ is the '
        r'change in Ensemble SR from the previous variant.}'
    )
    lines.append(r'\label{tab:ablation}')
    lines.append(r'\small')
    lines.append(r'\begin{tabular}{lccrrrr}')
    lines.append(r'\toprule')
    lines.append(
        r'\thead{Variant} & \thead{Target} & \thead{$K$} & '
        r'\thead{Ensemble SR} & \thead{Mean Seed SR} & \thead{Seed SD} & \thead{$\Delta$} \\'
    )
    lines.append(r'\midrule')
    for row in rows:
        variant = row.get('Variant', row.get('Variant_ID', ''))
        target = row.get('Target', '')
        accum = row.get('K', '')
        ens = row.get('Ensemble SR', row.get('Ensemble_SR', ''))
        mean = row.get('Mean Seed SR', row.get('Mean_Seed_SR', ''))
        sd = row.get('Seed SD', row.get('Std_Seed_SR', ''))
        delta = row.get('Delta', row.get('Delta_SR', '--'))
        lines.append(f'{variant} & {target} & {accum} & {ens} & {mean} & {sd} & {delta} \\\\')
    lines.append(r'\bottomrule')
    lines.append(r'\end{tabular}')
    lines.append(r'\end{table}')

    path = os.path.join(TABLE_DIR, 'table_ablation.tex')
    with open(path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    print(f"  Saved: {path}")


def gen_txcost():
    """Generate transaction-cost sensitivity table for CS-Gated +Onchain."""
    results, _, _, _ = load_results(
        os.path.join(CKPT_DIR, MODEL_FILES['cs_gated']),
        FEAT_CONFIGS,
    )
    metrics = compute_portfolio_metrics(
        results['+Onchain']['ensemble_preds'],
        results['+Onchain']['ensemble_tgts'],
        results['+Onchain']['ensemble_msks'],
    )
    preds, tgts, msks = metrics['_preds'], metrics['_tgts'], metrics['_msks']
    gross = metrics['sr_ew']
    breakeven = find_breakeven_cost(preds, tgts, msks, max_bps=2000)
    scenarios = [
        ('Gross', 0, 'No trading cost'),
        ('Maker-like', 5, 'Low-fee liquid execution'),
        ('Maker-like', 10, 'Maker fee plus small spread/slippage'),
        ('Taker-like', 25, 'Taker fee or moderate spread'),
        ('Taker-like', 50, 'Taker fee plus spread/slippage'),
        ('Stress', 100, 'High spread or market-impact allowance'),
        ('Stress', 200, 'Severe small-token execution allowance'),
    ]

    lines = []
    lines.append('% Auto-generated by gen_tables.py -- do not edit manually')
    lines.append(r'\begin{table}[t]')
    lines.append(r'\centering')
    lines.append(
        r'\caption[Transaction-cost sensitivity]{Transaction-cost sensitivity '
        r'for the CS-Gated \texttt{+Onchain} equal-weight long-short strategy.}'
    )
    lines.append(r'\label{tab:txcost}')
    lines.append(r'\small')
    lines.append(r'\setlength{\tabcolsep}{4pt}')
    lines.append(r'\begin{tabularx}{\linewidth}{@{}lrrr>{\raggedright\arraybackslash}X@{}}')
    lines.append(r'\toprule')
    lines.append(
        r'\thead{Scenario} & \thead{Cost} & \thead{Net SR} & '
        r'\thead{Avg. TO} & \thead{Interpretation} \\'
    )
    lines.append(r'\midrule')
    for label, bps, desc in scenarios:
        sr_net, _, avg_to = compute_sr_after_costs(preds, tgts, msks, bps)
        lines.append(
            f'{label} & {bps} bps & {sr_net:+.3f} & '
            f'{avg_to * 100:.1f}\\% & {desc} \\\\'
        )
    lines.append(r'\bottomrule')
    lines.append(r'\end{tabularx}')
    lines.append(r'\par\vspace{0.35em}')
    lines.append(r'\begin{minipage}{0.96\linewidth}')
    lines.append(r'\raggedright\footnotesize')
    lines.append(
        rf'\textit{{Note:}} Cost is an all-in one-way assumption applied to '
        rf'both long and short legs based on weekly portfolio turnover. '
        rf'Gross EW Sharpe is {gross:+.3f}; the estimated break-even '
        rf'one-way cost is approximately {breakeven:.0f} bps. These '
        rf'scenarios are sensitivity checks, not exchange-specific fee quotes.'
    )
    lines.append(r'\end{minipage}')
    lines.append(r'\end{table}')

    path = os.path.join(TABLE_DIR, 'table_txcost.tex')
    with open(path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    print(f"  Saved: {path}")


def gen_placeholders():
    """Keep optional table names available without overwriting real tables."""
    for name in ['table_cs_gated', 'table_lstm']:
        path = os.path.join(TABLE_DIR, name + '.tex')
        if not os.path.exists(path):
            with open(path, 'w', encoding='utf-8') as f:
                f.write(f'% Placeholder for {name}\n')
            print(f"  Created placeholder: {path}")


if __name__ == '__main__':
    print("=== Generating LaTeX tables ===")
    gen_cross_model()
    gen_ablation()
    gen_txcost()
    gen_placeholders()
    print("=== Done ===")
